### ISSUE TITLE
1.19-1.21 is broken

### ISSUE THREAD

**Issue by Lazerbrainzz** [tildejustin/custom-map-resetter#2]
mod crashes upon game launch

**Comment by tildejustin** [comment]
for what Minecraft version? the 1.19-1.20 build doesn't work past 1.20.4 as marked on Modrinth...

**Comment by Lazerbrainzz** [comment]
on 1.19.2. do i need fabric api? and what fabric loader do i use? right now I have 1.16.0

**Comment by tildejustin** [comment]
oh interesting, looks like it's broken pre 1.19.3, no ButtonWidget#DEFAULT_NARRATION_SUPPLIER. I can fix it later...

**Comment by Lazerbrainzz** [comment]
ok

**Comment by tildejustin** [comment]
fixed in v1.4.2
